// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiwvMOmyFRk7fQVPOMHm-bn-DNPB31L-4',
    appId: '1:666943458121:web:324c52aabd183acc49a898',
    messagingSenderId: '666943458121',
    projectId: 'zis-mobile',
    authDomain: 'zis-mobile.firebaseapp.com',
    storageBucket: 'zis-mobile.firebasestorage.app',
    measurementId: 'G-PM8T7EV55N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRL5C5hW2gld11OnKH8UIxKJ3VOgTbUNs',
    appId: '1:666943458121:android:e20d4272490a12bf49a898',
    messagingSenderId: '666943458121',
    projectId: 'zis-mobile',
    storageBucket: 'zis-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgQjsP9lMyfeiSp9UTUxTAh5BXN86jRE',
    appId: '1:666943458121:ios:806257e23110731849a898',
    messagingSenderId: '666943458121',
    projectId: 'zis-mobile',
    storageBucket: 'zis-mobile.firebasestorage.app',
    iosBundleId: 'com.example.zis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYgQjsP9lMyfeiSp9UTUxTAh5BXN86jRE',
    appId: '1:666943458121:ios:806257e23110731849a898',
    messagingSenderId: '666943458121',
    projectId: 'zis-mobile',
    storageBucket: 'zis-mobile.firebasestorage.app',
    iosBundleId: 'com.example.zis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiwvMOmyFRk7fQVPOMHm-bn-DNPB31L-4',
    appId: '1:666943458121:web:9cae413858add67149a898',
    messagingSenderId: '666943458121',
    projectId: 'zis-mobile',
    authDomain: 'zis-mobile.firebaseapp.com',
    storageBucket: 'zis-mobile.firebasestorage.app',
    measurementId: 'G-RKVC0CD6M4',
  );
}
